"""init

Revision ID: 7a13d6649633
Revises: 
Create Date: 2021-05-31 23:20:25.764241

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7a13d6649633'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('bad_records',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('merchant_identifier', sa.String(length=100), nullable=False, index=True),
                    sa.Column('reason', sa.String(length=100), nullable=False),
                    sa.Column('card_type', sa.Float(), nullable=False),
                    sa.Column('fullname', sa.String(length=100), nullable=False, index=True),
                    sa.Column('amount', sa.String(length=100), nullable=False),
                    sa.Column('create_at', sa.DateTime(), default=sa.func.current_timestamp()),
                    sa.Column('update_at', sa.DateTime(), onupdate=sa.ColumnDefault(sa.func.current_timestamp),
                              default=sa.func.current_timestamp()),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bad_records')
    # ### end Alembic commands ###
